### ISSUE TITLE
Monitor custom Tor events

### ISSUE THREAD

**Issue by parmegv** [robgjansen/onionperf#22]
Is it possible to monitor custom Tor events through the "--event" option?

Right now, https://github.com/robgjansen/onionperf/blob/3b2b9eb6102b932cca8da7de8d5622ad46aa262b/onionperf/onionperf#L123 you can only monitor events listed by get_supported_torctl_events() (https://github.com/robgjansen/onionperf/blob/3b2b9eb6102b932cca8da7de8d5622ad46aa262b/onionperf/monitor.py#L15). https://github.com/robgjansen/onionperf/blob/3b2b9eb6102b932cca8da7de8d5622ad46aa262b/onionperf/monitor.py#L15 basically lists stem.control.EventType.

**Comment by mjuarezm** [comment]
In the past we have modified `stem` to recognize these custom events. I don't know what is the best solution for this. @robgjansen: do you have any advices/ideas?

For instance, if we wanted to add a `CUSTOM_EVENT` type with args `arg1` and `arg2`, we were doing:
- In `control.py`:

> --- stem.original/control.py
> +++ stem.patched/control.py
> @@ -307,6 +307,9 @@
>    'TB_EMPTY',
>    'TRANSPORT_LAUNCHED',
>    'WARN',
> +  **'CUSTOM_EVENT',**
> ...
- In `events.py`:

> --- stem.original/response/events.py
> +++ stem.patched/response/events.py
> @@ -237,6 +237,13 @@
>      self.message = lines[2]
>      self.descriptor = '\n'.join(lines[3:-1])
> 
> +**class CustomEvent(Event):**
> +  **_POSITIONAL_ARGS = ('arg1', 'arg2')**
> 
>  class BandwidthEvent(Event):
>    """
> @@ -1328,4 +1335,8 @@
> 
>    # accounting for a bug in tor 0.2.0.22
>    'STATUS_SEVER': StatusEvent,
> +  **'CUSTOM_EVENT': CustomEvent,**
>  }

**Comment by robgjansen** [comment]
From OnionPerf's side, I think stem will return an error if we try to add an event that stem does not support. If stem doesn't support an event, we do catch the error [here](https://github.com/robgjansen/onionperf/blob/3b2b9eb6102b932cca8da7de8d5622ad46aa262b/onionperf/monitor.py#L43). So we could add `CUSTOM_EVENT` without crashing OnionPerf. However, I'm not sure if you will get any event output from Tor in this case.

Do you guys know what stem does if you send it an event that it doesn't know about? Does it still send it to Tor, and still send Tor's output back to the control port client (i.e., onionperf)?

**Comment by mjuarezm** [comment]
So, as far I can tell, the situation is:

stem exposes a "wrapper" around the tor controller that defines a set of "known events". This wrapper assigns a class to each known event which defines how to parse its event messages. For example, in the diff avove, `CUSTOM_EVENT` is the event type and `CustomEvent` is the class that defines how to parse `arg1` and `arg2` from the event message.

onionperf right now uses this high-level wrapper and thus assumes that stem will know about the events. However, there is the function `msg` in stem's wrapper:

https://stem.torproject.org/api/control.html#stem.control.BaseController

This function is not recommended but bypasses the wrapper and talks directly to the tor controller. I wonder if we could use this function in onionperf so that when we hit the exception for  unrecognized events, it falls back and tries to talk directly to the tor controller. Does this make sense?

**Comment by robgjansen** [comment]
Yeah, it seems like that could work. I wonder what stem does if you register for a new asynchronous event type using the `msg` function, and then Tor starts sending out those new events. Presumably stem will just pass these directly to the event callback in onionperf?

**Comment by mjuarezm** [comment]
Oh, I see. We would use [this](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n331) to register our custom async event, right? stem uses it too to register its "known events": https://gitweb.torproject.org/stem.git/tree/stem/control.py#n3755

> I wonder what stem does if you register for a new asynchronous event type using the msg function, and then Tor starts sending out those new events. Presumably stem will just pass these directly to the event callback in onionperf?

I'm not sure but, by reading stem's source code, it seems that it won't do anything for events that are not known. In [here](https://gitweb.torproject.org/stem.git/tree/stem/control.py#n929), it pulls for async event messages form the tor controller server and, then, it tries to find the event's handler. Since it doesn't know about the type of our custom event, it won't call any handler that onionperf might have registered:

https://gitweb.torproject.org/stem.git/tree/stem/control.py#n3716

hmm, I don't know. It seems stem strongly relies on the list of known events to assign the handlers. I don't see a clean way to do this right tnow.

**Comment by robgjansen** [comment]
Hmm, yeah I agree. I suggest the following:
1. Verify with Damian, the stem maintainer, that there is indeed no way to handle unknown custom asynchronous events.
2. Discuss with Damian if it makes sense to update stem so that it allows us to define a listener for asynchronous event types for which it doesn't have a known handler.
   - Ask Damian if he is willing to write this, or else offer to write it under his guidance.

In the meantime, we could just patch stem to handle the new custom event that you want to handle, and then OnionPerf will just automatically work correctly because the stem that OnionPerf is using will now know about your new custom event.

**Comment by mjuarezm** [comment]
Sounds good. Yes, we've been using the patched stem for now.

**Comment by mjuarezm** [comment]
I sent a PR for [this](https://github.com/robgjansen/onionperf/pull/23).
