### ISSUE TITLE
Persistent Onion service address

### ISSUE THREAD

**Issue by irl** [robgjansen/onionperf#42]
Currently it looks like the Onion service address changes with every restart. This makes monitoring more difficult.

**Comment by robgjansen** [comment]
@irl originally I did this in order to make it as simple as possible to run OnionPerf. But, your point about monitoring is a good one. I think the feature that should be added is e.g. a config option that allows the user to use a preconfigured onion address rather than using the ephemeral onion API and generating one on the fly.

Thanks for the request!

**Comment by irl** [comment]
I think it's possible to save the key that was used, so the config option could be a path to the file to store the key in so that you get the same one next time. On first run you'd generate the key.

The relevant ticket at Tor's Trac (about monitoring the Tor Metrics instances) is:
https://trac.torproject.org/projects/tor/ticket/28271

**Comment by irl** [comment]
This issue is now being tracked at https://trac.torproject.org/projects/tor/ticket/29366
